# azure-pipelines.yml

# Define the trigger for the pipeline
trigger:
  branches:
    include:
      - main  # Adjust this to the branch you want to monitor for changes

# Define the pool where the build will run
pool:
  vmImage: 'ubuntu-latest'  # You can also use 'windows-latest' or 'macOS-latest'

# Define the build stages
stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
          # Step to checkout the code from GitHub
          - checkout: self

          # Step to install Node.js (specify your required version)
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'  # Specify your Node.js version here
            displayName: 'Install Node.js (latest version)'

          # Step to install npm dependencies
          - script: |
              npm install
            displayName: 'Install Dependencies'

          # Step to build the React application
          - script: |
              npm run build
            displayName: 'Build React App'

               
              

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - job: Deploy
        displayName: 'Deployment Job'
        steps:
          # Step to deploy your application (replace with your deployment logic)
          - script: |
              echo "Deploying application..."
              # Add your deployment commands here (e.g., using Azure CLI or other services)
            displayName: 'Deploy Application'
