# Trigger the pipeline on changes to the main branch
trigger:
  branches:
    include:
      - main

# Use the latest Ubuntu VM image
pool:
  vmImage: 'ubuntu-latest'

# Define build and deployment stages
stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
          # Checkout code
          - checkout: self

          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          # Install npm dependencies
          - script: |
              cd app
              npm install
            displayName: 'Install Dependencies'

          # Build the application
          - script: |
              cd app
              npm run build
            displayName: 'Build Application'

          # Create a zip file of the application
          - script: |
              cd app
              zip -r ../node_app.zip .
            displayName: 'Create Node.js App ZIP'

          # Publish the artifact
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'node_app.zip'
              artifact: 'node_app'
            displayName: 'Publish Build Artifact'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: 
      - Build
      
    jobs:
      - job: Deploy
        displayName: 'Deployment Job'
        timeoutInMinutes: 120
        steps:
          # Download the artifact
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'node_app'
              path: '$(Pipeline.Workspace)'
            displayName: 'Download Build Artifact'

          # Install Terraform
          - script: |
              curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: 'Install Terraform'

          # Authenticate Azure CLI with Azure service principal
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Abel-serviceP-conn'  # Your Azure service connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Ensure correct Azure CLI authentication context
                az account set --subscription $(ARM_SUBSCRIPTION_ID)
                echo "Authenticated with Azure CLI."

          # Deploy the Node.js app
          - script: |
              az webapp deployment source config-zip \
                --resource-group "AbelDevopsRG33" \
                --name "AbelDevops23443" \
                --src "$(Pipeline.Workspace)/node_app.zip"  # Directly reference the file
            displayName: 'Deploy Node.js App to App Service'
